### ISSUE TITLE
Sometime message is None

### ISSUE THREAD

**Issue by egregors** [egregors/vldc-bot#25]
```
bot_1    | 2019-09-24 00:05:56,590 - skills.since_mode - INFO - topic from db for title I been gone is None
bot_1    | 2019-09-24 00:05:56,590 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
bot_1    | Traceback (most recent call last):
bot_1    |   File "/usr/local/lib/python3.7/site-packages/python_telegram_bot-12.0.0b1-py3.7.egg/telegram/ext/dispatcher.py", line 333, in process_update
bot_1    |     handler.handle_update(update, self, check, context)
bot_1    |   File "/usr/local/lib/python3.7/site-packages/python_telegram_bot-12.0.0b1-py3.7.egg/telegram/ext/handler.py", line 117, in handle_update
bot_1    |     return self.callback(update, context)
bot_1    |   File "/app/bot/skills/since_mode.py", line 79, in since_callback
bot_1    |     update.message.reply_text(
bot_1    | AttributeError: 'NoneType' object has no attribute 'reply_text'
```

**Comment by egregors** [comment]
did not reproduce
