### ISSUE TITLE
telegram.error.BadRequest: Chat not found

### ISSUE THREAD

**Issue by egregors** [egregors/vldc-bot#51]
```
2019-11-08 08:39:55,409 - telegram.utils.promise - ERROR - An uncaught error was raised while running the promise
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/python_telegram_bot-12.0.0b1-py3.7.egg/telegram/utils/promise.py", line 57, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/app/bot/skills/towel_mode.py", line 176, in ban_user
    chat_id = context.bot.get_chat(chat_id=context.job.context["chat_id"]).id
  File "/usr/local/lib/python3.7/site-packages/python_telegram_bot-12.0.0b1-py3.7.egg/telegram/bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/python_telegram_bot-12.0.0b1-py3.7.egg/telegram/bot.py", line 2159, in get_chat
    result = self._request.post(url, data, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/python_telegram_bot-12.0.0b1-py3.7.egg/telegram/utils/request.py", line 327, in post
    **urlopen_kwargs)
  File "/usr/local/lib/python3.7/site-packages/python_telegram_bot-12.0.0b1-py3.7.egg/telegram/utils/request.py", line 238, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Chat not found
```

**Comment by zemlya25** [comment]
this error usually caused by 400 error
2019-11-27 08:38:45,162 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "POST /bot812005415:AAEps50MQnaoXmSeSI_qO4YfLzIuOGDj1Og/getChat HTTP/1.1" 400 73

any thoughts?

**Comment by egregors** [comment]
Usually, if u doing smth wrong Tg sends you pretty accurate error details. IDK that actually was a reason for this cases

**Comment by moonbaseDelta** [comment]
>  
>  
> any thoughts?

Hide the token from request

**Comment by egregors** [comment]
Done. We should be just setup fight chat_id with @
