### ISSUE TITLE
Uwu is broken

### ISSUE THREAD

**Issue by egregors** [egregors/vldc-bot#79]
@moonbaseDelta 

```
2019-12-05 06:43:34,123 - telegram.utils.promise - ERROR - An uncaught error was raised while running the promise
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/python_telegram_bot-12.0.0b1-py3.7.egg/telegram/utils/promise.py", line 57, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/app/bot/skills/uwu.py", line 28, in uwu
    context.bot.send_photo(chat_id, photo=fairly_random_pic, caption="don't uwu! 😡")
  File "/usr/local/lib/python3.7/site-packages/python_telegram_bot-12.0.0b1-py3.7.egg/telegram/bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/python_telegram_bot-12.0.0b1-py3.7.egg/telegram/bot.py", line 404, in send_photo
    **kwargs)
  File "/usr/local/lib/python3.7/site-packages/python_telegram_bot-12.0.0b1-py3.7.egg/telegram/bot.py", line 123, in _message
    result = self._request.post(url, data, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/python_telegram_bot-12.0.0b1-py3.7.egg/telegram/utils/request.py", line 327, in post
    **urlopen_kwargs)
  File "/usr/local/lib/python3.7/site-packages/python_telegram_bot-12.0.0b1-py3.7.egg/telegram/utils/request.py", line 238, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Wrong file identifier/http url specified
```

**Comment by moonbaseDelta** [comment]
>
>
> file_id is unique for each individual bot and can't be transferred from one bot to another.

Надо попробовать с самого бота заливку произвести, возможно спасёт. 
Странная дрянь, только что наблюдал как помимо "Wrong file identifier/http url specified" были и дошедшие изображения.

**Comment by egregors** [comment]
> Там ботный api судя по всему как-то избирательно не пропускает file_id если они не сгенерированы то ли с сообщений изначально отправленных самим ботом по данному токену, то ли если их не было в личном чате с этим ботом. В python-telegram-bot об этой особенности как-то прямо не говорят, либо я совсем не то читал.  
> 
> Починить можно двумя путями:
> 1) Вернуть как раньше
> 2) Запустить бота с каноничным токеном и либо пусть где-нибудь в личном чате накидать ему желаемых пикч (либо самим ботом, либо с пользовательского акка ему) чтобы он себе file_id'шки надёргал и их уже просто в том массиве проставить.
> 
> Т.е. либо:
> 
> msg = bot.send_photo(...)
> консоль или файл << msg.photo[-1].file_id   # -1 индекс даст тот размер который отправлялся, другие варианты обычно уменьшенные
> 
> Либо тоже самое, но из апдейта от юзера

**Comment by egregors** [comment]
@moonbaseDelta could you please upload the archive with images and share the URL?
